CREATE TABLE [dbo].[BOARD_REPLY](
	[REPLY_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[BOARD_ID] [bigint] NOT NULL,
	[PARENT_ID] [bigint] NOT NULL,
	[DEPTH] [int] NOT NULL,
	[REPLY_CONTENT] [text] NOT NULL,
	[REPLY_WRITER] [varchar](100) NOT NULL,
	[REPLY_PASSWORD] [varchar](300) NOT NULL,
	[REGISTER_DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_BOARD_REPLY] PRIMARY KEY CLUSTERED 
(
	[REPLY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]